### PR TITLE
chore: remove unused dependency in packages/turbo-workspaces

### PR DESCRIPTION
**Pull request by torresgol10**
I have removed some dependencies that I have not found references to within your package in `packages/turbo-workspaces`.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 356462f0436272414cd72b7fb11492013edfed02

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by tknickman — APPROVED** [review]

**Comment by tknickman** [comment]
Looks good, thanks! This should auto merge once conflicts are resolved @torresgol10

**Comment by anthonyshew** [comment]
Uh oh, @torresgol10, we were betrayed by auto-merge on this one. Would you be able to fix the conflicts that have snuck in now that this sat for too long?

**Comment by torresgol10** [comment]
@anthonyshew All conflicts resolved

**Pull request merged**
