### PR TITLE
Referencing workspace packages through aliases in templates

### PR DESCRIPTION
**Pull request by initdc**

### CODE REVIEW

**Comment by jaredpalmer** [comment]
This is not supported by Yarn v1 unfortunately.

CleanShot 2021-12-14 at 10 25 32@2x
.

**Comment by initdc** [comment]
Right now, because the example packages cause conflicts with upstream, I think we need set the name of example packages more unique. Or better way, we can add a `scope` option when user run `create-turbo`

**Comment by initdc** [comment]
https://classic.yarnpkg.com/blog/2017/08/02/introducing-workspaces/
https://pnpm.io/workspaces

**Comment by jaredpalmer** [comment]
This still doesn't seem to work with Yarn v1 when the upstreams don't exist and all packages are private. 

CleanShot 2021-12-14 at 12 17 59@2x

**Comment by jaredpalmer** [comment]
Closing for now

**Pull request closed without merging**
