### PR TITLE
Add troubleshooting docs.

### PR DESCRIPTION
**Pull request by leerob**

### CODE REVIEW

**Comment by leerob** [comment]
Unsure why it isn't showing on the sidebar unless you navigate to it directly: https://turbo-site-git-troubleshooting.vercel.sh/docs/troubleshooting

**Review by jaredpalmer — APPROVED** [review]

**Comment by jaredpalmer** [comment]
@shuding any idea as to why this wouldn't show up in the sidebar even though it is present in meta.json ?

**Comment by shuding** [comment]
@jaredpalmer It seems we didn't rebuild all pages when meta.json is changed. Only an incremental build of the new page happened. Can you do a redeploy without cache? I'll get this fixed soon

**Comment by jaredpalmer** [comment]
Tried, even with no cache and --force. :thinking_taco:

CleanShot 2022-02-18 at 14 12 33@2x

**Pull request merged**
