### PR TITLE
Bump dependecies `jest`, `@types/jest` and `ts-jest`

### PR DESCRIPTION
**Pull request by torresgol10**
I upgraded the `jest`, `@types/jest` and `ts-jest` dependencies to the latest version, because in every `pnpm install` there was a warning for the ts-jest library and in the future I wanted to upgrade to typescript 5.5.3 in all packages.

In order to update `jest` it was necessary to update `ts-jest` and vice versa, although I didn't want to make a PR with both updates they are totally related and you can't update one library without updating the other.
 
In the `packages/turbo-test-utils`, I removed the `jest`, `@types/jest` and `ts-jest` dependencies, as they were not used in this package node:test is used.

In order to move from `jest` to the latest version and keep everything working the same without touching code, I had to update the configuration of jest when doing snapshop to leave the configuration that had before to be able to default, put it url of the documentation, without putting this configuration all the tests failed: https://jestjs.io/docs/upgrading-to-jest29#snapshot-format

In all jest configurations, now `InitialOptionsTsJest` is marked as deprecated and changed to `JestConfigWithTsJest`.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 169bedbb30fee3ec1ba2ef70391d00dafdb2eb85

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by mehulkar — APPROVED** [review]
Thank you!

**Comment by torresgol10** [comment]
Hi @anthonyshew, I think the auto merge failed

**Comment by anthonyshew** [comment]
Unfortunate. Looks like it did, indeed. Would you want to fix these conflicts or should we close and work on this some other time?

**Comment by torresgol10** [comment]
Hi @anthonyshew,

I have been checking and this has already been implemented: https://github.com/vercel/turborepo/pull/9155

I close this PR.

**Comment by anthonyshew** [comment]
Very sorry about that. I've encouraged and re-iterated with the team that we need to handle PRs from community members faster and always check for open PRs that have already done the work. Myself included, I've made mistakes on this a number of times.

We'll be better on this in the future and I continue to appreciate all your PRs. 🙏

**Comment by torresgol10** [comment]
It's OK, I'll keep doing PRs.

**Pull request closed without merging**
