### PR TITLE
chore(linting): implement ESLint flat config compatibility for `eslint-plugin-turbo`

### PR DESCRIPTION
**Pull request by jeremy-code**
### Description

- Add "flat/recommended" config to `eslint-plugin-turbo`
- Add `meta` property to plugin
- Update README.md accordingly with information on using flat config
- Add tests for flat config in `__tests__/cwdFlat.test.ts`

### Testing Instructions

Run the following command:

```shell
pnpm run test --filter=eslint-plugin-turbo
```

See vercel/turborepo#8606

### CODE REVIEW

**Comment by jeremy-code** [comment]
@anthonyshew This branch should be good, ran tests/lint/prettier.

**Comment by jeremy-code** [comment]
(That was just a rebase to catch up with 1 commit in main -- no lock file changes or anything)

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: ac39f63e19a4954e2edc5c9e51170007a5fccefb

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Review by anthonyshew — APPROVED** [review]
Amazing, thank you so much for being patient with us taking much too long to get back to you on this. Very excited for this - and I know many community members are as well!

**Comment by anthonyshew** [comment]
So glad to have merged this. Thank you again!

**Pull request merged**
