### PR TITLE
fix(docs): overflow on ` <Callout />`

### PR DESCRIPTION
**Pull request by QuiiBz**
When the content of `<Callout />` contains long elements considered as a single word (e.g inline code), it causes an overflow on the page, and we can zoom out / swipe to the right:

Screenshot 2022-09-26 at 15 49 32

This PR adds an `overflow-x: scroll;` to the container, which allows scrolling to the right similarly to code blocks: 

https://user-images.githubusercontent.com/43268759/192293690-ce9b1d6e-19f0-4276-9fe8-2beb1fd38691.mov

Another option is to break words, but I'm not sure if it's a better idea. The content is longer and breaks long words, such as inline code:

Screenshot 2022-09-26 at 15 50 45

### CODE REVIEW

**Comment by QuiiBz** [comment]
> Personally I prefer the word break option

Should we wait for someone else’s opinion, or go directly with word break?

**Comment by mattpocock** [comment]
@tknickman @QuiiBz Agree, word break looks better

**Comment by QuiiBz** [comment]
> @tknickman @QuiiBz Agree, word break looks better

Updated!

**Comment by tknickman** [comment]
Thanks @mattpocock / @QuiiBz

**Review by tknickman — APPROVED** [review]

**Pull request merged**
