### PR TITLE
feat(example): add angular getting started example

### PR DESCRIPTION
**Pull request by alydemah**

### CODE REVIEW

**Comment by anthonyshew** [comment]
Hi, thanks for this contribution!

I haven't gotten a chance to look over this whole PR - but I did notice quickly that the root README.md didn't get updated from the `basic` template. Could you take a look there and see what updates need to be made?

**Comment by alydemah** [comment]
Hi, 
@anthonyshew Thanks for the quick review, I noticed the missing readme and it should been updated now.

**Comment by codexshell** [comment]
Hello there folks.

Couldn't help but notice inconsistencies in the example. The most notable one is that the `ui` package is not any kind of angular library that am familiar with if such exists. More information on the status of the feature could be helpful.

Alternatively, I can have a complete example ready within the week. This can even include integration with storybook.  Am primarily an Angular Developer and am really excited about this feature (mostly because scaffolding a project with `nx` can take anywhere from 2 mins on a good day, to 20mins on a not so good one).

Am more than willing to take on the challenge and bring the idea to fruition.

**Comment by codexshell** [comment]
Just finished working on this feature, wondering whether I should open another pull request.

It's a complete example, similar (but slightly better) to the `svelte` example. It was actually inspired by it.

**Comment by anthonyshew** [comment]
Let's work together on #8140!

**Pull request closed without merging**
