### PR TITLE
Use GoReleaser for Builds

### PR DESCRIPTION
**Pull request by nathanhammond**
This is to enable using GoReleaser as a first step toward continuous delivery of build artifacts via CI. This is also the first step toward using CGO across a wider array of platforms.

### CODE REVIEW

**Comment by jaredpalmer** [comment]
A good reference for implementation could be Planetscale's CLI: https://github.com/planetscale/cli/blob/main/.goreleaser.yml

**Comment by nathanhammond** [comment]
Either we do a second script for moving assets into place after build (e.g. https://github.com/vercel/turborepo/pull/1455/commits/fbc81a89bbb5d446101044c8fbd81ef356bc086e#diff-04a30fd90db0e74acd7450aeade4bc2150c086d66cfe0c1048dab6dccddb3ecc) or this feature request sticks: https://github.com/goreleaser/goreleaser/issues/3215

**Comment by nathanhammond** [comment]
Related:
https://goreleaser.com/limitations/cgo/
https://github.com/goreleaser/goreleaser-cross

**Comment by nathanhammond** [comment]
This, with the failing test (!) is actually ready for review and to land.

The failing test is because it is installing `turbo@1.3.3` during the install step, and this PR changes the path of the asset.

https://github.com/vercel/turborepo/runs/7440069115?check_suite_focus=true#step:8:79

It will work correctly once:
- This PR is merged.
- A new version is pushed to the `latest` tag on `npm` using this release process.

**Review by tknickman — APPROVED** [review]
Looks good, I don't have a great way to test this locally so relying on you for the actual release testing since you have the go releaser 🔑  - but the approach looks sound. 

Only callout is moving the `version.txt` to root. This makes sense if we're versioning all the packages along with `turbo` itself (which we _can_) but if we're not 100% on that yet, or we deviate, that could cause confusion. 

I could see us wanting to keep versions separate - for example `create-turbo` has no strict dependency on `turbo` itself, and we likely won't _need_ to push major changes to the packages (with the exception of `turbo-ignore` since it shells out to `turbo`, but even that depends on the scope of the breaking CLI change) when turbo has a new major. 

But, keeping everything lockstep as you suggested is definitely the simpler approach.

**Pull request merged**
