### PR TITLE
feat: move lockfile logic into backends

### PR DESCRIPTION
**Pull request by Xenfo**
## Related:
- implements https://github.com/vercel/turborepo/pull/544#discussion_r784026108.

## What this PR brings:
This PR moves lockfile logic out of `context.go` and into it's specific backend as per https://github.com/vercel/turborepo/pull/544#discussion_r784026108.

### CODE REVIEW

**Comment by Xenfo** [comment]
I'm a bit confused with what you want. I have it so that it goes through the keys each backend provides (only yarn and yarn berry is supported so the other backends have empty arrays) and gets the lockfile entry.

**Comment by Xenfo** [comment]
> I'm a bit confused with what you want. I have it so that it goes through the keys each backend provides (only yarn and yarn berry is supported so the other backends have empty arrays) and gets the lockfile entry. Do you want it to resolve the entry in the backend and not in context?

@jaredpalmer I need further guidance on this.

**Comment by gsoltis** [comment]
@Xenfo IIUC, the idea would be to remove usages of `util.IsYarn` from `context.go` and instead have the relevant functionality baked into the backend.

**Comment by jaredpalmer** [comment]
Are you still working on this?

**Comment by Xenfo** [comment]
Yeah I'll try to finish it this weekend.

**Comment by Xenfo** [comment]
Took a look, and I'm not sure how to move it, some things are `context` specific.

**Pull request closed without merging**
