### PR TITLE
Bump semver & types to latest version

### PR DESCRIPTION
**Pull request by torresgol10**
I have updated the `semver` and `@types/semver` library to the latest version available in `packages/turbo-workspaces`. I have also removed `semver` from devDependency as it was duplicated.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 77e0653681300cccafe7734b812685c2367fac3e

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by anthonyshew** [comment]
Seems the lockfile needs updating?: https://github.com/vercel/turbo/actions/runs/9882553757/job/27406797799?pr=8716

**Comment by torresgol10** [comment]
@anthonyshew Yes, it looks like it needs to be updated. Already updated! 😊

**Comment by anthonyshew** [comment]
@torresgol10 I apologize for you leaving you hanging as long as I did. I was out on parental leave. Would you be able to/want to fix up the new set of conflicts so we can merge this?

**Comment by torresgol10** [comment]
@anthonyshew Don't worry, nothing is wrong, I have already solved the problem and updated a pending minor one.

**Review by anthonyshew — APPROVED** [review]
Thanks!

**Pull request merged**
