### PR TITLE
bug fix on design-system example

### PR DESCRIPTION
**Pull request by zsh77**
### Description

- add `preview-storybook` task to turbo.json and it's script in the root's package.json
- improvement on clean script
- changed the tsup config of `@acme/ui` package not to make source map files in order to match the content of `ui/dist` directory stated in README of root
- bug fix of README file. Replaced `acme-core` and other names that  meant to point to packages/ui with `@acme/ui`

### Testing Instructions

Running `npx create-turbo@latest -e design-system` and then `pnpm dev` should work and start storybook in dev mode. README.md file in the root should be fine too.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 664a4a95cf4991936d3ac3c791e5ccafaae053ef

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by zsh77** [comment]
@anthonyshew I'm just making sure in case you've missed this PR. Thank you in advance for your review!

**Comment by du5rte** [comment]
A lot of the examples are broken. I applied this PR changes over `npx create-turbo@latest -e design-system` and worked like a charm. Thank you @zsh77 !

**Comment by zsh77** [comment]
> A lot of the examples are broken. I applied this PR changes over `npx create-turbo@latest -e design-system` and worked like a charm. Thank you @zsh77 !

Happy it helped you @du5rte !

**Pull request closed without merging**
