### PR TITLE
docs: Fix typos

### PR DESCRIPTION
**Pull request by jayvdb**
### Description

Fix typos using https://crates.io/crates/typos-cli

I can add the `.typos.toml` if that is desirable.

While the changes extend beyond docs, the only visible impact of this change will be the fixes in the docs.

### CODE REVIEW

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 0b3ea0e080b45d28846c855d53f66d1fffc38d33

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by ijjk** [comment]
Allow CI Workflow Run

- [ ] approve CI run for commit: 0b3ea0e080b45d28846c855d53f66d1fffc38d33

Note: this should only be enabled once the PR is ready to go and can only be enabled by a maintainer

**Comment by jayvdb** [comment]
Many of the CI failures appear to be because I am not authorised.

The docs CI failure appears to be a bug in `src/validate-docs-links.ts`.  When I debug it to see which headers it detects in https://github.com/vercel/turborepo/blob/main/docs/repo-docs/guides/tools/typescript.mdx , it shows

```
┌─────────┬───────────────────────────────────────────────────────────────────┐
│ (index) │ Values                                                            │
├─────────┼───────────────────────────────────────────────────────────────────┤
│ 0       │ 'sharing-tsconfigjson'                                            │
│ 1       │ 'use-a-base-tsconfig-file'                                        │
│ 2       │ 'creating-the-rest-of-the-package'                                │
│ 3       │ 'building-a-typescript-package'                                   │
│ 4       │ 'using-the-configuration-package'                                 │
│ 5       │ 'creating-entrypoints-to-the-package'                             │
│ 6       │ 'linting-your-codebase'                                           │
│ 7       │ 'best-practices'                                                  │
│ 8       │ 'use-tsc-to-compile-your-packages'                                │
│ 9       │ 'use-nodejs-subpath-imports-instead-of-typescript-compiler-paths' │
│ 10      │ 'just-in-time-packages'                                           │
└─────────┴───────────────────────────────────────────────────────────────────┘
```

i.e. the parser fails in "Just-in-Time packages" - probably the `<Tabs..` construct, which also breaks the github rendering of the page.  cc @anthonyshew who authored https://github.com/vercel/turborepo/pull/8958 .  I note that the rehype & remark deps in `package.json` are extremely outdated - actually almost all of the deps are at least a major version behind the latest release.

**Comment by anthonyshew** [comment]
Yup, you're right on all accounts. That link validator broke somehow right before I went on parental leave, unfortunately. I'll try to fix that as soon as I can Thank you for the fixes and I'll merge once CI passes!

**Pull request merged**
