### PR TITLE
Rename go module to allow command line installs

### PR DESCRIPTION
**Pull request by dglsparsons**
The `go install` command doesn't like it when the go.mod file
declares a different path to the module, to the actual path.

e.g.

```
$ go install github.com/vercel/turborepo/cli/cmd/turbo@latest
go install: github.com/vercel/turborepo/cli/cmd/turbo@latest: github.com/vercel/turborepo/cli@v0.0.0-20211216165811-9163f2518d55: parsing go.mod:
	module declares its path as: turbo
	        but was required as: github.com/vercel/turborepo/cli
```

This PR renames the go module to match the path name, as go expects. This allows the turborepo CLI to be installed via `go install`

### CODE REVIEW

**Comment by jaredpalmer** [comment]
I think this complicates #397 quite a bit?

**Comment by jaredpalmer** [comment]
we should do it for the go doc though I guess

**Comment by dglsparsons** [comment]
I think you could probably work out if the binary is in $GOBIN and prompt for go install for the latest version in that instance?

**Comment by jaredpalmer** [comment]
We should do this, but probs easier to just take main and search + replace at this point.

**Comment by dglsparsons** [comment]
Yeah. Almost certainly is. I'll get it rebased on Monday for you.

**Review by jaredpalmer — APPROVED** [review]

**Pull request merged**
