### PR TITLE
fix: modern yarn lockfile parsing error

### PR DESCRIPTION
**Pull request by erj826**
## Description
The header string written to the pruned lockfile by the `turbo prune` command starts each of the metadata fields at the beginning of a line. This causes the `__metadata`, `version`, and `cache_key` fields to be parsed as separate fields, when really the `version` and `cache_key` should be nested within `__metadata`.  This silently causes the yarn cache to miss on every dependency without throwing an error. Fixing this line drastically improves dependency install times for pruned workspaces when the cache exists. Additionally, turbo throws an error [here](https://github.com/vercel/turborepo/blob/main/cli/internal/fs/lockfile.go#L81) when running a `yarn workspaces focus my-app` install afterwards due to the un-nested metadata:

```
ERROR  yarn.lock: could not unmarshal lockfile: yaml: unmarshal errors:
--
  |   | line 5: cannot unmarshal !!int `5` into fs.LockfileEntry
  |   | line 6: cannot unmarshal !!int `8` into fs.LockfileEntry
```

## Solution
Because the [yamlEncoder](https://github.com/vercel/turborepo/blob/main/cli/internal/prune/prune.go#L245) sets the indent to two, adding two spaces before each of the fields should make this valid syntax.

Before:
```yaml
__metadata:
version: 5
cacheKey: 8
```

After:
```yaml
__metadata:
  version: 5
  cacheKey: 8
```

## Env
Yarn v3.2.2
Turborepo v1.3.4

### CODE REVIEW

**Comment by tknickman** [comment]
@erj826 thanks for this! Out of curiosity what version of yarn are you using?

**Comment by erj826** [comment]
> @erj826 thanks for this! Out of curiosity what version of yarn are you using?

@tknickman yarn 3.2.2

**Comment by tknickman** [comment]
Thanks for the additional info, this looks good. 

I was playing around with it locally, and with the same version yarn auto corrects the formatting in my pruned `yarn.lock` (from an install in `/out` post prune). I didn't try with focus however. 

That being said the current behavior is definitely not correct so this fix looks great.

**Comment by tknickman** [comment]
@erj826 FYI ya'll might run into some issues with prune on yarn v3.

There was some discussion (and a subset or your changes) here:
https://github.com/vercel/turborepo/pull/643

**Comment by quinnturner** [comment]
Somewhat humourous, despite this improving the format of the lockfile, this breaks `turbo prune` on our project for Yarn v3. Of course, `prune` is not expected to work, but it _kind of_ did.

Now, I get `Internal Error: Assertion failed: Expected the lockfile entry to have a resolution field (@ampproject/remapping@npm:^2.1.0)`

**Comment by erj826** [comment]
@quinnturner now it seems like yarn is able to parse the lockfile and catch that the prune-generated lockfile doesn't include the resolution field -- which [your comment](https://github.com/vercel/turborepo/pull/643#issuecomment-1122855212) on #643 looks like it'll fix?

**Comment by quinnturner** [comment]
Exactly, yep! @erj826 I have a WIP that may or may not work out where I expand on that change by fully supporting Yarn Berry as a backend. My goal is to split up the Lockfile definition into separate definitions, one per backend. No promises though, as I am newer to go and have other commitments 😄

**Pull request merged**
