### PR TITLE
feat: switch to cobra

### LINKED ISSUE #758: "panic: runtime error: slice bounds out of range" with --concurrency 1
### What version of Turborepo are you using?

1.1.3

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Running the example repo, this command fails:
```
$ turbo run lint --concurrency 1
panic: runtime error: slice bounds out of range [14:13]

goroutine 1 [running]:
github.com/vercel/turborepo/cli/internal/run.parseRunArgs({0xc00013a020, 0x3, 0x3}, {0xc000024034, 0x27})
	github.com/vercel/turborepo/cli/internal/run/run.go:833 +0x1e05
github.com/vercel/turborepo/cli/internal/run.(*RunCommand).Run(0xc00000c180, {0xc00013a020, 0x0, 0x0})
	github.com/vercel/turborepo/cli/internal/run/run.go:122 +0x25c
github.com/mitchellh/cli.(*CLI).Run(0xc00016ba40)
	github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
main.main.func9(0x8df223, {0x0, 0x38}, {0xc00013a010, 0x7f5b55bc65b8, 0x4}, {0x0, 0xc00013a820}, {0x0, 0x0}, ...)
	github.com/vercel/turborepo/cli/cmd/turbo/main.go:173 +0x445
main.main()
	github.com/vercel/turborepo/cli/cmd/turbo/main.go:178 +0xc25

```

### Expected Behavior

No panic.

### To Reproduce

1. Checkout https://github.com/vercel/turborepo/tree/a3c066bf0c59ba2faa133e3420f23487ae7065d9/examples/basic
2. run `yarn install`
3. run `yarn turbo run lint --concurrency 1`

### LINKED ISSUE #759: Move to pflag/viper or cobra
### Describe the feature you'd like to request

Because we manually parse CLI args, users are getting stuck with the inflexible syntax. 

See #758 
### Describe the solution you'd like

Switch to viper and pflags for config and flags parsing 

Or

Switch to Cobra and drop mitchelh/cli. This would also let us auto generate documentation

### Describe alternatives you've considered

N/A

### PR DESCRIPTION
**Pull request by Xenfo**
**What this PR brings:**
- Links all added Cobra commands into `cmd/root.go`
- Adds tracing, heap and profiling support
- Deletes all old command files and removes old CLI framework
- Introduces `cmdutil` which gives access to the config and logger in a command while providing common helper functions

**Needed PRs:**
- Info commands
  - [x] `bin` command (#906)
- Authentication commands
  - [ ] `link` command (no PR yet)
  - [ ] `login` command (no PR yet)
  - [x] `logout` command (#1204)
  - [x] `unlink` command (#1203)
- Run commands
  - [ ] `run` command (no PR yet)
- Prune commands
  - [ ] `prune` command (no PR yet)

**Related Issues:**
- closes #758
- closes #759

**Similar Projects for Reference:**
- https://github.com/cli/cli
- https://github.com/planetscale/cli

### CODE REVIEW

**Comment by Xenfo** [comment]
Hey @jaredpalmer can you give me some pointers on how you want this done? I created the bin command but not sure how you want stuff like logging done.

**Comment by Xenfo** [comment]
@jaredpalmer I've done some more work, can you take a look and tell me what's good and what's bad before I start the big commands?

**Comment by gsoltis** [comment]
@Xenfo I'll defer to @jaredpalmer on the specifics, but one suggestion I have is to try to break this up a bit. It's going to be very difficult to review a complete switch over all at once. Some things to consider might be doing a command-at-a-time, or even a command-per-commit in the final PR if you want the ultimate change to be atomic.

**Comment by Xenfo** [comment]
I'll switch everything to cobra here then make individual PRs for everything, I think that would be easier for me.

**Comment by nathanhammond** [comment]
Hey @Xenfo! We have slowly but surely ported most everything over to Cobra. I'm wondering if you feel like there are pieces in this PR that still need to be split out and landed or if we're in a good place to close this PR as a completed task?

**Comment by Xenfo** [comment]
This PR is meant to be a placeholder for linking everything to Cobra in the end so I don't think it should be closed yet. I'll pick this PR up again soon since I'm in finals now and can't work on it.

**Pull request closed without merging**
