### PR TITLE
Support yarn 3 lockfile entries

### PR DESCRIPTION
**Pull request by theJoeBiz**
The yarn berry support is looking good, but I can't truly use `turbo prune` with yarn 3 because the `checksum`, `resolution`  and `linkType` properties aren't being carried over. I updated the `LockfileEntry` struct locally and tested it out - here is the side-by-side comparison of root `yarn.lock` and `out/yarn.lock`:

Screen Shot 2022-01-30 at 12 19 01 AM

Btw, not sure how important the `__metadata` key is in the lockfile, but I think it'd be ideal if that was copied directly

### CODE REVIEW

**Comment by Xenfo** [comment]
It only partly works for me. Been working on this for a while, trying to get `yarn --immutable` to work
lEcER0br
.

**Comment by theJoeBiz** [comment]
> It only partly works for me. Been working on this for a while, trying to get `yarn --immutable` to work !

Ah, you're right. It looks like my "soft" links (the monorepo packages) are missing from the pruned lockfile. Perhaps something to do with version parsing? Example:
```yaml
"@***/admin@workspace:apps/admin":
  version: 0.0.0-use.local
  resolution: "@***/admin@workspace:apps/admin"
  dependencies:
    ...
```

**Comment by Xenfo** [comment]
Probably, when I implemented Yarn 3 I didn't realize how much there was, I probably missed a bunch of stuff.

**Comment by theJoeBiz** [comment]
I am seeing the workspace packages listed in the `node_modules/.cache/turbo/{}-turbo-lock.yaml` file, but looks like the "workspace: *" versions aren't wrapped in quotes like they are in the root yarn.lock:

Screen Shot 2022-01-30 at 11 21 24 AM
Screen Shot 2022-01-30 at 11 23 43 AM

**Comment by theJoeBiz** [comment]
@jaredpalmer I haven't had a chance to go back and look at this again since I left it, but IIRC the local workspaces weren't listed in `yarn.lock` for v1. I'm wondering if workspace packages are specifically being filtered out of the final list.

**Comment by Xenfo** [comment]
I'm not entirely sure if that's the case, I was just running `yarn install --immutable` and fixing one thing at a time eg: double quote missing here, add it.

**Comment by jaredpalmer** [comment]
We'd need to go through and fix --immutable line by line

**Comment by quinnturner** [comment]
This change, as is, makes my `yarn install` work on a pruned project. While it doesn't support `--immutable`, without this change, I cannot perform a `yarn install` on a pruned project at all due to a `501` error from the Yarn registry. Please consider releasing this change despite it not working with `--immutable` as it turns my non-working project into a working project.

**Comment by chris-olszewski** [comment]
Hi all, with #1789 we should be able to better support different types of lockfiles. Once that merges, I'll begin looking at updating this PR to use the new abstraction.

**Comment by theJoeBiz** [comment]
@chris-olszewski That's great! I haven't had much time to dedicate to this, but I'm looking forward to checking out the new abstraction.

**Comment by quinnturner** [comment]
Similarly, I haven't been able to dedicate as much time to my WIP PR. However, I have implemented a few changes in my draft https://github.com/quinnturner/turborepo/pull/2 that are required for full support. My checklist above is in an accurate state. 

Things that are solved:

- `yarn.lock`'s `__metadata` header are maintained from the source `yarn.lock` and formatted correctly (the metadata content is not static across all Berry versions)
- Separating the lockfile definition between Classic/Berry (as they are _very_ different)
- Full lockfile definition implementation (`peerDependencies`, `peerDependenciesMeta`, etc.) with correct sorting of those keys
- Post-prune deduping and quoting fixes (tricky, but seemingly solved; required a lot of manual indexing/substringing/parsing -> adding quotes)


Things there are not solved:

- Sorting is difficult because the YAML parser that we use decides to sort characters like `^` differently compared to Berry's natural sorting algorithm
- I hadn't figured out how to add workspace package references to the destination lockfile while also maintaining the correct formatting. i.e., keys in the destination `lockfile` like: `"@internal/shared-package@*, @internal/shared-package@workspace:*".

**Comment by weyert** [comment]
> FYI: `yarn` has `yarn workspaces focus` command to install dependencies of exact workspace

Yeah `pnpm` has `pnpm deploy` but don't think they want to depend on such commands

**Comment by nathanhammond** [comment]
@theJoeBiz we suspect that this has been superseded by https://github.com/vercel/turborepo/pull/2019, with support released in 1.5.

Thank you for the early pass which helped us understand the shape of the problem!

**Pull request closed without merging**
