### PR TITLE
QoL changes for using examples

### PR DESCRIPTION
**Pull request by markjm**
1. Always use the locally built turbo binary to support easier usage within the examples. Similar to how it is done in the `run-examples` script, but for local use as well.
2. differentiate logged output when cache is missed vs when execution is forced
3. Hide the big error object from printing to console when execution fails. See before and after
image
Not sure what the thinking is on what else to write out on failure, but i suspect whatever message should come from the main turborepo program and not the node wrapper.

Loving digging around the project! Feel free to accept or reject any number of pieces of this changeset.

### CODE REVIEW

**Comment by markjm** [comment]
I have actually identified an issue when running a fresh yarn install with TURBO_BINARY_PATH set. Seems to be  because of differences in directories when running the postinstall script vs an actual `turbo` command - which prevents using a relative path in yarnrc

**Comment by jaredpalmer** [comment]
Why do we need .yarnc?

**Comment by markjm** [comment]
> Why do we need .yarnc?

the intent is that regardless of platform or mode of running the examples, it will always use the repo-built version of the app by having this univeral way of specifying process.env varialbes. Given there are some other differences with usage of that env variable (and now thinking i dont know if pnmp or other backends would even support this), I will remove that change to unblock the rest of the PR

**Comment by jaredpalmer** [comment]
In the future, these should likely be separate PRs, but other than that this looks fine. Thanks!

**Review by jaredpalmer — APPROVED** [review]

**Comment by markjm** [comment]
> In the future, these should likely be separate PRs, but other than that this looks fine. Thanks!

Fair - thanks for the help

**Review by jaredpalmer — APPROVED** [review]

**Pull request merged**
