### PR TITLE
chore: fix formatting

### PR DESCRIPTION
**Pull request by Xenfo**

### CODE REVIEW

**Comment by gsoltis** [comment]
@Xenfo what formatting setup are you using? Some of these match the output from what I'm using (`gopls` via VSCode), but some do not. We probably ought to standardize so that there isn't churn.

**Comment by jaredpalmer** [comment]
@gsoltis can we follow uber's style guide and use their suggest golint in ci? https://github.com/uber-go/guide/blob/master/.golangci.yml

**Comment by Xenfo** [comment]
@gsoltis I'm using the format bellow.

```go
import (
  // Native imports

  // Turbo imports

  // Third party imports
)
```

**Comment by gsoltis** [comment]
@Xenfo I think @jaredpalmer's suggestion is the best way to tackle this. I'm going to suggest that we close this in favor of an issue to properly set up CI to enforce these things: #934

**Comment by Xenfo** [comment]
Does it allow for import sorting?

**Comment by gsoltis** [comment]
It defers to [`goimports`](https://pkg.go.dev/golang.org/x/tools/cmd/goimports)

**Comment by Xenfo** [comment]
Alright

**Pull request closed without merging**
