### PR TITLE
Apply global ignore patterns for global deps

### LINKED ISSUE #720: Global dependencies always cause tree walk
### What version of Turborepo are you using?

1.1.2

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

If a `globalDependencies` entry is a single file (in our case a base tsconfig), it [still causes a full tree walk](https://github.com/vercel/turborepo/blob/0c24f5a620c4429809714616aec358f8bf560af7/cli/internal/context/context.go#L176). On Linux machines (tested under WSL2 on Windows and a bare metal Linux machine) this is quite performant (300-500ms overhead), but much slower on the OS X machines we use (~5-10s overhead depending on model). Removing `globalDependencies` makes a very noticeable improvement to any invocation of `turbo`.

### Expected Behavior

A single file global dependency (no `$` and no glob wildcard characters) should only check for that file, not initiate a full tree walk.

### To Reproduce

On OS X, add some files to `globalDependencies` and compare build times with and without. Our repository is private and I'm not sure how to go about creating a large enough test case.

### PR DESCRIPTION
**Pull request by Kingwl**
Closes #720

Most of time is walking about node_modules who we should ignore.

### CODE REVIEW

**Review by jaredpalmer — APPROVED** [review]

**Comment by jaredpalmer** [comment]
Woops. Good catch!

**Comment by jaredpalmer** [comment]
@elado this may have been what was slowing you down fyi

**Comment by elado** [comment]
@jaredpalmer it improved things (35s -> 22s) but still not perfect.
node_modules files are about 180k files
Entire repo is around 500k files

**Comment by jaredpalmer** [comment]
We are going to fix globbing shortly and should be massive win

**Comment by Kingwl** [comment]
> node_modules files are about 180k files
> Entire repo is around 500k files

Wow......

**Pull request merged**
