### PR TITLE
test: add integration test with AWS SDK for JavaScript v3

### PR DESCRIPTION
**Pull request by trivikr**
### Description

From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.

This PR updates `aws-sdk` integration test to use v3

### Testing Instructions

CI

### CODE REVIEW

**Comment by trivikr** [comment]
cc active contributors @sokra @tknickman for review

**Comment by sokra** [comment]
This should probably a new separate test case. We want to continue to test the older version.

**Comment by trivikr** [comment]
> This should probably a new separate test case

Added as a separate test case in https://github.com/vercel/turbo/pull/6352/commits/9157c33186471ed7b7ffb3be9461d137ae2c1544

**Comment by anthonyshew** [comment]
Closing as stale, since Turbopack is no longer in the repo!

**Pull request closed without merging**
